<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Kaizentro</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kaizentro.Application\Kaizentro.Application.csproj" />
    <ProjectReference Include="..\Kaizentro.Domain\Kaizentro.Domain.csproj" />
  </ItemGroup>
</Project>
